/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    identities: IdentityAuthOperations;
  };
  blocks: {};
  collections: {
    identities: Identity;
    trips: Trip;
    'trip-content': TripContent;
    memberships: Membership;
    invitations: Invitation;
    polls: Poll;
    'poll-options': PollOption;
    votes: Vote;
    'login-tokens': LoginToken;
    'health-checks': HealthCheck;
    'audit-entries': AuditEntry;
    media: Media;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    identities: IdentitiesSelect<false> | IdentitiesSelect<true>;
    trips: TripsSelect<false> | TripsSelect<true>;
    'trip-content': TripContentSelect<false> | TripContentSelect<true>;
    memberships: MembershipsSelect<false> | MembershipsSelect<true>;
    invitations: InvitationsSelect<false> | InvitationsSelect<true>;
    polls: PollsSelect<false> | PollsSelect<true>;
    'poll-options': PollOptionsSelect<false> | PollOptionsSelect<true>;
    votes: VotesSelect<false> | VotesSelect<true>;
    'login-tokens': LoginTokensSelect<false> | LoginTokensSelect<true>;
    'health-checks': HealthChecksSelect<false> | HealthChecksSelect<true>;
    'audit-entries': AuditEntriesSelect<false> | AuditEntriesSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: Identity;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface IdentityAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "identities".
 */
export interface Identity {
  id: string;
  displayName?: string | null;
  /**
   * Avatar image URL.
   */
  avatar?: string | null;
  role?: ('admin' | 'user') | null;
  /**
   * Per-user UI + system-message language (PRD §6).
   */
  preferredLanguage?: ('cs' | 'en') | null;
  preferredChannel?: ('email' | 'whatsapp' | 'telegram' | 'inapp') | null;
  providers?:
    | {
        provider: 'google' | 'microsoft';
        providerAccountId: string;
        email?: string | null;
        id?: string | null;
      }[]
    | null;
  contactChannels?:
    | {
        type: 'email' | 'phone' | 'telegram';
        value: string;
        label?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  password?: string | null;
  collection: 'identities';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "trips".
 */
export interface Trip {
  id: string;
  name: string;
  /**
   * Used in payment messages (PRD §8.1). Keep it short.
   */
  shortName: string;
  location?: string | null;
  description?: string | null;
  /**
   * Per-trip branding (PRD §8.1, §12).
   */
  theme?: {
    /**
     * Accent color, e.g. #3b82f6.
     */
    color?: string | null;
    /**
     * Emoji glyph branding the trip.
     */
    icon?: string | null;
    /**
     * Uploaded cover photo (stored in MongoDB/GridFS).
     */
    coverMedia?: (string | null) | Media;
    /**
     * Optional cover image URL override (used if no upload).
     */
    coverImage?: string | null;
  };
  /**
   * Which areas the group collaborates on (PRD §8.1).
   */
  enabledAreas?: {
    voting?: boolean | null;
    sleeping?: boolean | null;
    transport?: boolean | null;
    lists?: boolean | null;
    finances?: boolean | null;
    deposit?: boolean | null;
  };
  phase?: ('draft' | 'ideation' | 'planning' | 'finances' | 'archived') | null;
  datePollState?: ('open' | 'closed') | null;
  locationPollState?: ('open' | 'closed') | null;
  rosterState?: ('open' | 'locked') | null;
  financeState?: ('open' | 'settling' | 'closed') | null;
  /**
   * Promoted from the date poll when it closes (T-305).
   */
  dates?: {
    start?: string | null;
    end?: string | null;
  };
  /**
   * Banker bank details for settlement QR codes (PRD §8.5.4).
   */
  banker?: {
    /**
     * The banker Membership (also flagged isBanker).
     */
    membership?: (string | null) | Membership;
    /**
     * Czech account, e.g. 123456789/0100.
     */
    bankAccount?: string | null;
    iban?: string | null;
  };
  /**
   * Deposit-to-confirm config (PRD §8.3.2).
   */
  deposit?: {
    enabled?: boolean | null;
    /**
     * Provisional until paid. Always on when deposit is enabled.
     */
    gated?: boolean | null;
    /**
     * The required basis is the participant's planned-cost share (T-501).
     */
    basis?: 'plannedCost' | null;
  };
  /**
   * Invite settings (PRD §5).
   */
  invites?: {
    /**
     * Per-trip shareable join link. Off by default.
     */
    openJoinEnabled?: boolean | null;
    /**
     * Approve open-join requests automatically. Approval is required by default.
     */
    openJoinAutoAccept?: boolean | null;
    /**
     * The open-join link's shareable token. Unlike auth tokens (magic link / invites) this is stored in the clear, because it's a non-secret, approval-gated link the organizer needs to re-display and share repeatedly.
     */
    openJoinToken?: string | null;
  };
  /**
   * Identity that created the trip (the first organizer).
   */
  createdBy?: (string | null) | Identity;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  /**
   * Accessibility description.
   */
  alt?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "memberships".
 */
export interface Membership {
  id: string;
  trip: string | Trip;
  /**
   * Null until the invitee logs in and claims the pending membership.
   */
  identity?: (string | null) | Identity;
  /**
   * Organizer pre-fill; falls back to the Identity's display name once claimed.
   */
  displayName?: string | null;
  role?: ('organizer' | 'co-organizer' | 'participant') | null;
  status?: ('pending' | 'active') | null;
  /**
   * The participant who holds the shared money (PRD §8.5).
   */
  isBanker?: boolean | null;
  /**
   * Deposit-confirmed (banker-driven, T-506). Provisional until set.
   */
  confirmed?: boolean | null;
  /**
   * Self-service attendance (T-401 expands this).
   */
  attendance?: {
    status?: ('coming' | 'not' | 'maybe') | null;
    arrival?: string | null;
    departure?: string | null;
    companions?: number | null;
    pet?: boolean | null;
  };
  /**
   * Czech account for refunds (PRD §8.5.4).
   */
  bankAccount?: string | null;
  iban?: string | null;
  preferredChannelOverride?: ('email' | 'whatsapp' | 'telegram' | 'inapp') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "trip-content".
 */
export interface TripContent {
  id: string;
  /**
   * The trip this content belongs to (one row per trip).
   */
  trip: string | Trip;
  /**
   * The destination block (PRD §8.7).
   */
  destination?: {
    /**
     * e.g. Chata Pod Lysou.
     */
    name?: string | null;
    /**
     * Address / area, e.g. Krásná 142 · Beskydy.
     */
    location?: string | null;
    /**
     * Open-in-Maps link.
     */
    mapUrl?: string | null;
    description?: string | null;
    /**
     * Quick-facts grid (check-in, Wi-Fi, sleeps, nightly rate, …).
     */
    basicInfo?:
      | {
          label: string;
          value: string;
          id?: string | null;
        }[]
      | null;
    /**
     * Useful links (booking, reviews, house rules).
     */
    links?:
      | {
          label: string;
          url: string;
          id?: string | null;
        }[]
      | null;
    photos?:
      | {
          url: string;
          caption?: string | null;
          id?: string | null;
        }[]
      | null;
    /**
     * Free-form bullets (PRD §8.7 basic-info).
     */
    goodToKnow?:
      | {
          text: string;
          id?: string | null;
        }[]
      | null;
  };
  /**
   * Driving directions per origin (PRD §8.3.4 reference).
   */
  directions?:
    | {
        /**
         * From where, e.g. Brno.
         */
        origin: string;
        /**
         * e.g. 2 h 10 min.
         */
        duration?: string | null;
        /**
         * e.g. 180 km.
         */
        distance?: string | null;
        /**
         * Route notes / turn-by-turn.
         */
        notes?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Parking info at the destination.
   */
  parking?: string | null;
  /**
   * Public-transport options (PRD §8.3.4).
   */
  publicTransport?:
    | {
        /**
         * Line / service, e.g. R 18 Beskydy.
         */
        line: string;
        from?: string | null;
        to?: string | null;
        /**
         * Departure time(s).
         */
        departs?: string | null;
        /**
         * Arrival time(s).
         */
        arrives?: string | null;
        notes?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * House / trip notes shown to everyone (PRD §8.7).
   */
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "invitations".
 */
export interface Invitation {
  id: string;
  trip: string | Trip;
  /**
   * The pending membership this invitation activates.
   */
  membership?: (string | null) | Membership;
  targetType?: ('email' | 'phone' | 'handle' | 'name') | null;
  /**
   * Email / phone / handle / name the invite was addressed to.
   */
  targetValue: string;
  /**
   * SHA-256 of the invite token. The raw token is never stored.
   */
  tokenHash: string;
  status?: ('pending' | 'accepted' | 'expired') | null;
  source?: ('direct' | 'open-link') | null;
  expiresAt: string;
  /**
   * When the invite was redeemed (single-use replay guard).
   */
  acceptedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "polls".
 */
export interface Poll {
  id: string;
  trip: string | Trip;
  kind: 'date' | 'location';
  /**
   * Date polls use approval or grid; location polls use single or approval.
   */
  method?: ('approval' | 'grid' | 'single') | null;
  /**
   * Draft while the organizer seeds options; published opens voting.
   */
  published?: boolean | null;
  /**
   * Set when the poll is closed and the winner is promoted to the trip.
   */
  winnerOption?: (string | null) | PollOption;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "poll-options".
 */
export interface PollOption {
  id: string;
  poll: string | Poll;
  trip: string | Trip;
  kind: 'date' | 'location';
  /**
   * Date polls: window start.
   */
  dateStart?: string | null;
  /**
   * Date polls: window end.
   */
  dateEnd?: string | null;
  /**
   * Location polls: the place; also a display label for date windows.
   */
  label?: string | null;
  /**
   * The participant who suggested it; null = organizer-seeded.
   */
  suggestedBy?: (string | null) | Membership;
  /**
   * Moderated out of the vote.
   */
  hidden?: boolean | null;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "votes".
 */
export interface Vote {
  id: string;
  poll: string | Poll;
  trip: string | Trip;
  option: string | PollOption;
  membership: string | Membership;
  value: 'yes' | 'ifneeded' | 'no';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "login-tokens".
 */
export interface LoginToken {
  id: string;
  /**
   * Email the magic link was issued for (lowercased).
   */
  email: string;
  /**
   * Resolved at mint time when the email already has an Identity.
   */
  identity?: (string | null) | Identity;
  tokenHash: string;
  expiresAt: string;
  /**
   * Set on first redemption; a used token is rejected (replay protection).
   */
  usedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "health-checks".
 */
export interface HealthCheck {
  id: string;
  note: string;
  ok?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "audit-entries".
 */
export interface AuditEntry {
  id: string;
  /**
   * Who performed the action (null for system actions).
   */
  actor?: (string | null) | Identity;
  /**
   * Dotted action key, e.g. finance.accounts.closed.
   */
  action: string;
  targetType: string;
  targetId: string;
  /**
   * Trip id the entry belongs to (queryable). Kept as a plain id, not a relationship, so the audit trail stays valid even if a trip is later removed — an audit log must not lose entries to referential cleanup.
   */
  trip?: string | null;
  metadata?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: string;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'identities';
        value: string | Identity;
      } | null)
    | ({
        relationTo: 'trips';
        value: string | Trip;
      } | null)
    | ({
        relationTo: 'trip-content';
        value: string | TripContent;
      } | null)
    | ({
        relationTo: 'memberships';
        value: string | Membership;
      } | null)
    | ({
        relationTo: 'invitations';
        value: string | Invitation;
      } | null)
    | ({
        relationTo: 'polls';
        value: string | Poll;
      } | null)
    | ({
        relationTo: 'poll-options';
        value: string | PollOption;
      } | null)
    | ({
        relationTo: 'votes';
        value: string | Vote;
      } | null)
    | ({
        relationTo: 'login-tokens';
        value: string | LoginToken;
      } | null)
    | ({
        relationTo: 'health-checks';
        value: string | HealthCheck;
      } | null)
    | ({
        relationTo: 'audit-entries';
        value: string | AuditEntry;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'identities';
    value: string | Identity;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'identities';
    value: string | Identity;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "identities_select".
 */
export interface IdentitiesSelect<T extends boolean = true> {
  displayName?: T;
  avatar?: T;
  role?: T;
  preferredLanguage?: T;
  preferredChannel?: T;
  providers?:
    | T
    | {
        provider?: T;
        providerAccountId?: T;
        email?: T;
        id?: T;
      };
  contactChannels?:
    | T
    | {
        type?: T;
        value?: T;
        label?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "trips_select".
 */
export interface TripsSelect<T extends boolean = true> {
  name?: T;
  shortName?: T;
  location?: T;
  description?: T;
  theme?:
    | T
    | {
        color?: T;
        icon?: T;
        coverMedia?: T;
        coverImage?: T;
      };
  enabledAreas?:
    | T
    | {
        voting?: T;
        sleeping?: T;
        transport?: T;
        lists?: T;
        finances?: T;
        deposit?: T;
      };
  phase?: T;
  datePollState?: T;
  locationPollState?: T;
  rosterState?: T;
  financeState?: T;
  dates?:
    | T
    | {
        start?: T;
        end?: T;
      };
  banker?:
    | T
    | {
        membership?: T;
        bankAccount?: T;
        iban?: T;
      };
  deposit?:
    | T
    | {
        enabled?: T;
        gated?: T;
        basis?: T;
      };
  invites?:
    | T
    | {
        openJoinEnabled?: T;
        openJoinAutoAccept?: T;
        openJoinToken?: T;
      };
  createdBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "trip-content_select".
 */
export interface TripContentSelect<T extends boolean = true> {
  trip?: T;
  destination?:
    | T
    | {
        name?: T;
        location?: T;
        mapUrl?: T;
        description?: T;
        basicInfo?:
          | T
          | {
              label?: T;
              value?: T;
              id?: T;
            };
        links?:
          | T
          | {
              label?: T;
              url?: T;
              id?: T;
            };
        photos?:
          | T
          | {
              url?: T;
              caption?: T;
              id?: T;
            };
        goodToKnow?:
          | T
          | {
              text?: T;
              id?: T;
            };
      };
  directions?:
    | T
    | {
        origin?: T;
        duration?: T;
        distance?: T;
        notes?: T;
        id?: T;
      };
  parking?: T;
  publicTransport?:
    | T
    | {
        line?: T;
        from?: T;
        to?: T;
        departs?: T;
        arrives?: T;
        notes?: T;
        id?: T;
      };
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "memberships_select".
 */
export interface MembershipsSelect<T extends boolean = true> {
  trip?: T;
  identity?: T;
  displayName?: T;
  role?: T;
  status?: T;
  isBanker?: T;
  confirmed?: T;
  attendance?:
    | T
    | {
        status?: T;
        arrival?: T;
        departure?: T;
        companions?: T;
        pet?: T;
      };
  bankAccount?: T;
  iban?: T;
  preferredChannelOverride?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "invitations_select".
 */
export interface InvitationsSelect<T extends boolean = true> {
  trip?: T;
  membership?: T;
  targetType?: T;
  targetValue?: T;
  tokenHash?: T;
  status?: T;
  source?: T;
  expiresAt?: T;
  acceptedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "polls_select".
 */
export interface PollsSelect<T extends boolean = true> {
  trip?: T;
  kind?: T;
  method?: T;
  published?: T;
  winnerOption?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "poll-options_select".
 */
export interface PollOptionsSelect<T extends boolean = true> {
  poll?: T;
  trip?: T;
  kind?: T;
  dateStart?: T;
  dateEnd?: T;
  label?: T;
  suggestedBy?: T;
  hidden?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "votes_select".
 */
export interface VotesSelect<T extends boolean = true> {
  poll?: T;
  trip?: T;
  option?: T;
  membership?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "login-tokens_select".
 */
export interface LoginTokensSelect<T extends boolean = true> {
  email?: T;
  identity?: T;
  tokenHash?: T;
  expiresAt?: T;
  usedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "health-checks_select".
 */
export interface HealthChecksSelect<T extends boolean = true> {
  note?: T;
  ok?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "audit-entries_select".
 */
export interface AuditEntriesSelect<T extends boolean = true> {
  actor?: T;
  action?: T;
  targetType?: T;
  targetId?: T;
  trip?: T;
  metadata?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}