/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    identities: IdentityAuthOperations;
  };
  blocks: {};
  collections: {
    identities: Identity;
    trips: Trip;
    memberships: Membership;
    invitations: Invitation;
    'login-tokens': LoginToken;
    'health-checks': HealthCheck;
    'audit-entries': AuditEntry;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    identities: IdentitiesSelect<false> | IdentitiesSelect<true>;
    trips: TripsSelect<false> | TripsSelect<true>;
    memberships: MembershipsSelect<false> | MembershipsSelect<true>;
    invitations: InvitationsSelect<false> | InvitationsSelect<true>;
    'login-tokens': LoginTokensSelect<false> | LoginTokensSelect<true>;
    'health-checks': HealthChecksSelect<false> | HealthChecksSelect<true>;
    'audit-entries': AuditEntriesSelect<false> | AuditEntriesSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: Identity;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface IdentityAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "identities".
 */
export interface Identity {
  id: string;
  displayName?: string | null;
  /**
   * Avatar image URL.
   */
  avatar?: string | null;
  role?: ('admin' | 'user') | null;
  /**
   * Per-user UI + system-message language (PRD §6).
   */
  preferredLanguage?: ('cs' | 'en') | null;
  preferredChannel?: ('email' | 'whatsapp' | 'telegram' | 'inapp') | null;
  providers?:
    | {
        provider: 'google' | 'microsoft';
        providerAccountId: string;
        email?: string | null;
        id?: string | null;
      }[]
    | null;
  contactChannels?:
    | {
        type: 'email' | 'phone' | 'telegram';
        value: string;
        label?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  password?: string | null;
  collection: 'identities';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "trips".
 */
export interface Trip {
  id: string;
  name: string;
  /**
   * Used in payment messages (PRD §8.1). Keep it short.
   */
  shortName: string;
  location?: string | null;
  description?: string | null;
  /**
   * Per-trip branding (PRD §8.1, §12).
   */
  theme?: {
    /**
     * Accent color, e.g. #3b82f6.
     */
    color?: string | null;
    icon?: string | null;
    /**
     * Cover/background image URL.
     */
    coverImage?: string | null;
  };
  /**
   * Which areas the group collaborates on (PRD §8.1).
   */
  enabledAreas?: {
    voting?: boolean | null;
    sleeping?: boolean | null;
    transport?: boolean | null;
    lists?: boolean | null;
    finances?: boolean | null;
    deposit?: boolean | null;
  };
  phase?: ('draft' | 'ideation' | 'planning' | 'finances' | 'archived') | null;
  datePollState?: ('open' | 'closed') | null;
  locationPollState?: ('open' | 'closed') | null;
  rosterState?: ('open' | 'locked') | null;
  financeState?: ('open' | 'settling' | 'closed') | null;
  /**
   * Promoted from the date poll when it closes (T-305).
   */
  dates?: {
    start?: string | null;
    end?: string | null;
  };
  /**
   * Banker bank details for settlement QR codes (PRD §8.5.4).
   */
  banker?: {
    /**
     * The banker Membership (also flagged isBanker).
     */
    membership?: (string | null) | Membership;
    /**
     * Czech account, e.g. 123456789/0100.
     */
    bankAccount?: string | null;
    iban?: string | null;
  };
  /**
   * Deposit-to-confirm config (PRD §8.3.2).
   */
  deposit?: {
    enabled?: boolean | null;
    /**
     * Provisional until paid. Always on when deposit is enabled.
     */
    gated?: boolean | null;
    /**
     * The required basis is the participant's planned-cost share (T-501).
     */
    basis?: 'plannedCost' | null;
  };
  /**
   * Invite settings (PRD §5).
   */
  invites?: {
    /**
     * Per-trip shareable join link. Off by default.
     */
    openJoinEnabled?: boolean | null;
    /**
     * Approve open-join requests automatically. Approval is required by default.
     */
    openJoinAutoAccept?: boolean | null;
    /**
     * SHA-256 of the open-join link token (the raw token is never stored).
     */
    openJoinTokenHash?: string | null;
  };
  /**
   * Identity that created the trip (the first organizer).
   */
  createdBy?: (string | null) | Identity;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "memberships".
 */
export interface Membership {
  id: string;
  trip: string | Trip;
  /**
   * Null until the invitee logs in and claims the pending membership.
   */
  identity?: (string | null) | Identity;
  /**
   * Organizer pre-fill; falls back to the Identity's display name once claimed.
   */
  displayName?: string | null;
  role?: ('organizer' | 'co-organizer' | 'participant') | null;
  status?: ('pending' | 'active') | null;
  /**
   * The participant who holds the shared money (PRD §8.5).
   */
  isBanker?: boolean | null;
  /**
   * Deposit-confirmed (banker-driven, T-506). Provisional until set.
   */
  confirmed?: boolean | null;
  /**
   * Self-service attendance (T-401 expands this).
   */
  attendance?: {
    status?: ('coming' | 'not' | 'maybe') | null;
    arrival?: string | null;
    departure?: string | null;
    companions?: number | null;
    pet?: boolean | null;
  };
  /**
   * Czech account for refunds (PRD §8.5.4).
   */
  bankAccount?: string | null;
  iban?: string | null;
  preferredChannelOverride?: ('email' | 'whatsapp' | 'telegram' | 'inapp') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "invitations".
 */
export interface Invitation {
  id: string;
  trip: string | Trip;
  /**
   * The pending membership this invitation activates.
   */
  membership?: (string | null) | Membership;
  targetType?: ('email' | 'phone' | 'handle' | 'name') | null;
  /**
   * Email / phone / handle / name the invite was addressed to.
   */
  targetValue: string;
  /**
   * SHA-256 of the invite token. The raw token is never stored.
   */
  tokenHash: string;
  status?: ('pending' | 'accepted' | 'expired') | null;
  source?: ('direct' | 'open-link') | null;
  expiresAt: string;
  /**
   * When the invite was redeemed (single-use replay guard).
   */
  acceptedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "login-tokens".
 */
export interface LoginToken {
  id: string;
  /**
   * Email the magic link was issued for (lowercased).
   */
  email: string;
  /**
   * Resolved at mint time when the email already has an Identity.
   */
  identity?: (string | null) | Identity;
  tokenHash: string;
  expiresAt: string;
  /**
   * Set on first redemption; a used token is rejected (replay protection).
   */
  usedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "health-checks".
 */
export interface HealthCheck {
  id: string;
  note: string;
  ok?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "audit-entries".
 */
export interface AuditEntry {
  id: string;
  /**
   * Who performed the action (null for system actions).
   */
  actor?: (string | null) | Identity;
  /**
   * Dotted action key, e.g. finance.accounts.closed.
   */
  action: string;
  targetType: string;
  targetId: string;
  /**
   * Trip id the entry belongs to (queryable). Kept as a plain id, not a relationship, so the audit trail stays valid even if a trip is later removed — an audit log must not lose entries to referential cleanup.
   */
  trip?: string | null;
  metadata?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: string;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'identities';
        value: string | Identity;
      } | null)
    | ({
        relationTo: 'trips';
        value: string | Trip;
      } | null)
    | ({
        relationTo: 'memberships';
        value: string | Membership;
      } | null)
    | ({
        relationTo: 'invitations';
        value: string | Invitation;
      } | null)
    | ({
        relationTo: 'login-tokens';
        value: string | LoginToken;
      } | null)
    | ({
        relationTo: 'health-checks';
        value: string | HealthCheck;
      } | null)
    | ({
        relationTo: 'audit-entries';
        value: string | AuditEntry;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'identities';
    value: string | Identity;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'identities';
    value: string | Identity;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "identities_select".
 */
export interface IdentitiesSelect<T extends boolean = true> {
  displayName?: T;
  avatar?: T;
  role?: T;
  preferredLanguage?: T;
  preferredChannel?: T;
  providers?:
    | T
    | {
        provider?: T;
        providerAccountId?: T;
        email?: T;
        id?: T;
      };
  contactChannels?:
    | T
    | {
        type?: T;
        value?: T;
        label?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "trips_select".
 */
export interface TripsSelect<T extends boolean = true> {
  name?: T;
  shortName?: T;
  location?: T;
  description?: T;
  theme?:
    | T
    | {
        color?: T;
        icon?: T;
        coverImage?: T;
      };
  enabledAreas?:
    | T
    | {
        voting?: T;
        sleeping?: T;
        transport?: T;
        lists?: T;
        finances?: T;
        deposit?: T;
      };
  phase?: T;
  datePollState?: T;
  locationPollState?: T;
  rosterState?: T;
  financeState?: T;
  dates?:
    | T
    | {
        start?: T;
        end?: T;
      };
  banker?:
    | T
    | {
        membership?: T;
        bankAccount?: T;
        iban?: T;
      };
  deposit?:
    | T
    | {
        enabled?: T;
        gated?: T;
        basis?: T;
      };
  invites?:
    | T
    | {
        openJoinEnabled?: T;
        openJoinAutoAccept?: T;
        openJoinTokenHash?: T;
      };
  createdBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "memberships_select".
 */
export interface MembershipsSelect<T extends boolean = true> {
  trip?: T;
  identity?: T;
  displayName?: T;
  role?: T;
  status?: T;
  isBanker?: T;
  confirmed?: T;
  attendance?:
    | T
    | {
        status?: T;
        arrival?: T;
        departure?: T;
        companions?: T;
        pet?: T;
      };
  bankAccount?: T;
  iban?: T;
  preferredChannelOverride?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "invitations_select".
 */
export interface InvitationsSelect<T extends boolean = true> {
  trip?: T;
  membership?: T;
  targetType?: T;
  targetValue?: T;
  tokenHash?: T;
  status?: T;
  source?: T;
  expiresAt?: T;
  acceptedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "login-tokens_select".
 */
export interface LoginTokensSelect<T extends boolean = true> {
  email?: T;
  identity?: T;
  tokenHash?: T;
  expiresAt?: T;
  usedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "health-checks_select".
 */
export interface HealthChecksSelect<T extends boolean = true> {
  note?: T;
  ok?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "audit-entries_select".
 */
export interface AuditEntriesSelect<T extends boolean = true> {
  actor?: T;
  action?: T;
  targetType?: T;
  targetId?: T;
  trip?: T;
  metadata?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}